# Generated by Django 5.2.9 on 2025-12-03 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_enrollment_course_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollment',
            options={'ordering': ['-enrollment_date']},
        ),
        migrations.AlterModelOptions(
            name='enrollmentrequest',
            options={'ordering': ['-priority', '-requested_at']},
        ),
        migrations.AddField(
            model_name='enrollmentrequest',
            name='priority',
            field=models.IntegerField(default=0, help_text='Higher number = higher priority'),
        ),
        migrations.AlterField(
            model_name='enrollmentrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('waitlisted', 'Waitlisted')], default='pending', max_length=15),
        ),
    ]
