# Generated by Django 5.2.9 on 2025-12-04 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_enrollment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='enrollment_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollmentrequest',
            name='enrollment_deadline',
            field=models.DateTimeField(blank=True, help_text='Enrollment request deadline', null=True),
        ),
    ]
