# Generated by Django 5.2.9 on 2025-12-04 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_enrollment_deadline'),
        ('students', '0004_enrollment_enrollment_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='enrolled_courses',
            field=models.ManyToManyField(related_name='students', through='students.Enrollment', to='courses.course'),
        ),
    ]
