# Generated by Django 5.2.9 on 2025-12-03 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='openings',
            field=models.PositiveIntegerField(default=20),
        ),
    ]
