# Generated by Django 5.2.9 on 2025-12-04 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_openings'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='enrollment_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
